resolver: nightly-2017-09-26

packages:
- .
- location:
    git: https://github.com/biocad/monique-core.git
    commit: 0.2.1.2
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

ghc-options:
  "*": -Wall
