resolver: lts-9.0

packages:
- .
- location:
    git: https://github.com/biocad/monique-core.git
    commit: 0.2.1.1
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

ghc-options:
  "*": -Wall
